### ISSUE TITLE
XSL dependency

### ISSUE THREAD

**Issue by odolany** [pkp/oaiJats#2]
I added this plugin to my ojs3 and in plugins list I have a message by its entry: "WARNING: This plugin requires XSL support, which is currently not present on your system.", could you please write a bit on that in the plugin's description?

**Comment by asmecher** [comment]
@odolany, I actually removed that dependency without removing the note about it. I've removed the stated dependency: https://github.com/pkp/oaiJats/commit/4e9ea0db2f779d7bbf40af67d3da18aea326df8c
