### ISSUE TITLE
Grant access to embargoed content via API Key

### ISSUE THREAD

**Issue by ewhanson** [pkp/oaiJats#22]
**Describe the problem you would like to solve**
Be able to harvest/access embargoed content via JATS OAI by supplying an API key with the necessary permissions to access embargoed content (e.g. Subscription Manager). 

Erudit's metadata harvesting process previously believed this to be the case and had accessing embargoed content successfully because of a previous bug that always made embargoed content accessible regardless of requester's subscription status (see: https://github.com/pkp/oaiJats/commit/610e4202bf0ece5da297fe0957e12f04ab42b397). When attempting to access embargoed content now, this message is returned: `Cannot disseminate format (JATS XML not available)`.

**Describe the solution you'd like**
Add an additional check in the code section below to get the user from the API key and check if it has access to the embargoed content (method of authorization check TBD).

https://github.com/pkp/oaiJats/blob/886b9c4e84e65679a1831e59aad78686b8821024/OAIMetadataFormat_JATS.inc.php#L90-L96

**Who is asking for this feature?**
This request comes from Erudit, which has been harvesting JATS OAI metadata under the assumption this was already the case.

**Additional information**
This specific issue is limited to the `oaiJATS` plugin, at least in part, because the JATS includes full text.

**Comment by ewhanson** [comment]
@asmecher, what do you think of this approach? Is there anything else I should consider when looking at this? Thanks!

**Comment by asmecher** [comment]
@ewhanson, could you test/review https://github.com/pkp/oaiJats/pull/24? I think this might be all that's required. The subscription manager wasn't getting an automatic pass by virtue of having that role. The API key is already tested/used in OJS core code -- see https://github.com/pkp/pkp-lib/issues/4428 for details.

**Comment by ewhanson** [comment]
Thanks @asmecher, this is great. I tested it out and it's working as expected (provides the XML with an authorized API key, denies access without one).

**Comment by asmecher** [comment]
Thanks, @ewhanson! Merged and forward-ported to `main`.
