### ISSUE TITLE
Always include article-id[publisher-id]

### ISSUE THREAD

**Issue by ewhanson** [pkp/oaiJats#25]
If the incoming JATS from `OAIMetadataFormat_JATS::_findJATS()` does not include an `<article-id pub-id-type="publisher-id">` tag, one is not currently added before appearing in the OAI record. This can be added as part of `OAIMetadataFormat_JATS::_mungeMetadata()` to ensure each XML document includes the publisher ID.

**Comment by ewhanson** [comment]
Hey @asmecher, could you take a look at these? It makes sure the `<article-id pub-id-type="publisher-id">` tag is included even if input JATS does not include it? 

Also, it looks like the tests are failing to get off the ground, erroring out at the `npm i g -npm && npm install && npm run build` step.

Thanks!

PRs:
- `main`: #26
- `stable-3_3_0`: #27

**Comment by asmecher** [comment]
Thanks, @ewhanson, I'll look into why the tests have been broken (that's not your doing)!
