### ISSUE TITLE
Keyword groups in multilingual journals duplicated

### ISSUE THREAD

**Issue by ewhanson** [pkp/oaiJats#30]
Any keyword groups that have been added previously are supposed to be removed in `_mungeMetadata()` in the line below, but only the first node is ever removed. If an article has  more than one set of `kwd-group` tags for multilingual keywords, the remaining sets will remain and be duplicated once OJS adds back in its own set of keywords.

https://github.com/pkp/oaiJats/blob/d611794518dc74cab863473ac252e4f516a3d6d1/OAIMetadataFormat_JATS.inc.php#L286

Example:

![Screen Shot 2022-05-10 at 13 00 25](https://user-images.githubusercontent.com/20844845/167712116-3e52710a-a1f3-4439-8f83-5b1ec4faeda6.png)

**Comment by ewhanson** [comment]
Hey @asmecher, could you have a look at this? I've made a PR against `stable-3_3_0`, but if this approach looks okay, I can make a PR against `main` as well. Thanks!

PR: 
- #31

**Comment by asmecher** [comment]
This weird `getElementsByTagName` / `removeChild` behavior doesn't appear to be documented anywhere I can see it, but it's alluded to here:
https://www.php.net/manual/en/domnode.removechild.php#90292

Please go ahead with a port to `main`, thanks!

**Comment by ewhanson** [comment]
Thanks @asmecher! I've created a PR against `main`.

PR:

- #32

**Comment by asmecher** [comment]
Merged, thanks!
