### ISSUE TITLE
Use publication seq for article sequence information

### ISSUE THREAD

**Issue by ewhanson** [pkp/oaiJats#35]
**Issue:** Article sequence order is not behaving as expected in the OAI JATS output. 

Currently the submission ID + 1 is used as the article sequence attached to the `volume`/`issue` nodes. This does not take the publication's stored `seq` into account, so if an issue has it's submissions reordered, this new order won't be reflected in the OAI JATS.

**Considerations:** Would using the publication `seq` directly result in any conflicts. Are the publication's `seq` unique across an issue or just a section?

**Proposal:** Use the publication `seq` field instead of the submission ID, e.g.:

```diff
foreach (['volume', 'issue'] as $nodeName) {
	$match = $xpath->query("//article/front/article-meta/$nodeName");
	if ($match->length) {
-		$match->item(0)->setAttribute('seq', array_search($article->getId(), $articleIds)+1);
+		$match->item(0)->setAttribute('seq', ((int) $publication->getData('seq')) + 1);
		break;
	}
}
```

@asmecher, do you see any issues with this approach?

**Comment by asmecher** [comment]
@ewhanson, sorry for the wait. No, I don't think there will be any issue with this per the JATS standard (the [`seq` attribute definition](https://jats.nlm.nih.gov/archiving/tag-library/1.1/attribute/seq.html) is very general; our `seq` data point will be number but it's actually stored as a float in the database and may not be contiguous).

Better check with @giotta, though -- are there any assumptions on the Erudit side about what the values of the `seq` attribute to the `volume` and `issue` entities will be in the JATS XML produced by OJS?

**Comment by pigeonm** [comment]
@asmecher also sorry for the wait. Erudit will look for the seq attribute on the issue first, then on the volume (if absent from the issue). Also, for the seq value, Erudit is expecting it to be a number that matches the article's place in the issue.

**Comment by ewhanson** [comment]
Hey @asmecher, could you review these? I've made the changes as suggested above. Thanks!

PRs:
- `stable-3_3_0`: #37
- `stable-3_4_0`: #38 
- `main`: #39

**Comment by asmecher** [comment]
All merged, thanks, @ewhanson!
