### ISSUE TITLE
Uncaught TypeError: PKP\submissionFile\Repository::get()

### ISSUE THREAD

**Issue by lordzik2012** [pkp/oaiJats#52]
Hello,
we're getting this error on oaiJats v. 1.0.5.1, OJS 3.4.0.6:

PHP Fatal error:  Uncaught TypeError: PKP\submissionFile\Repository::get(): Argument #1 ($id) must be of type int, null given, called in /home/xxx/public_html/plugins/oaiMetadataFormats/oaiJats/OAIMetadataFormat_JATS.php on line 47 and defined in /home/xxx/public_html/lib/pkp/classes/submissionFile/Repository.php:76
Stack trace:
#0 /home/xxx/public_html/plugins/oaiMetadataFormats/oaiJats/OAIMetadataFormat_JATS.php(47): PKP\submissionFile\Repository->get()
#1 /home/xxx/public_html/plugins/oaiMetadataFormats/oaiJats/OAIMetadataFormat_JATS.php(107): APP\plugins\oaiMetadataFormats\oaiJats\OAIMetadataFormat_JATS->_findJats()
#2 /home/xxx/public_html/lib/pkp/classes/oai/OAI.php(825): APP\plugins\oaiMetadataFormats\oaiJats\OAIMetadataFormat_JATS->toXml()
#3 /home/xxx/public_html/lib/pkp/classes/oai/OAI.php(566): PKP\oai\OAI->formatMetadata()
#4 /home/xxx/public_html/lib/pkp/classes/oai/OAI.php(95): PKP\oai\OAI->ListRecords()
#5 /home/xxx/public_html/pages/oai/OAIHandler.php(47): PKP\oai\OAI->execute()
#6 [internal function]: APP\pages\oai\OAIHandler->index()
#7 /home/xxx/public_html/lib/pkp/classes/core/PKPRouter.php(334): call_user_func()
#8 /home/xxx/public_html/lib/pkp/classes/core/PKPPageRouter.php(277): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest()
#9 /home/xxx/public_html/lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPPageRouter->route()
#10 /home/xx/public_html/lib/pkp/classes/core/PKPApplication.php(388): PKP\core\Dispatcher->dispatch()
#11 /home/xx/public_html/index.php(21): PKP\core\PKPApplication->execute()
#12 {main}
  thrown in /home/xxx/public_html/lib/pkp/classes/submissionFile/Repository.php on line 76

Can you fix it?

**Comment by asmecher** [comment]
@lordzik2012, you should be able to resolve this by applying https://github.com/pkp/oaiJats/commit/7df59ee996b45f5ccf937157b9c0004a335fdd6b.
