### ISSUE TITLE
DOI text nodes are doubled up

### ISSUE THREAD

**Issue by jnugent** [pkp/oaiJats#53]
Seen in `stable-3_3_0`, probably also in `3.4` and `main`

If this line of code executes:

https://github.com/pkp/oaiJats/blob/stable-3_3_0/OAIMetadataFormat_JATS.inc.php#L341

The resulting OAI XML contains a doubled up doi with it being repeated twice in the node. Example:

`<article-id pub-id-type="doi" >10.18357/kula.24710.18357/kula.247</article-id>`

The DOI retrieved from the article here:

https://github.com/pkp/oaiJats/blob/stable-3_3_0/OAIMetadataFormat_JATS.inc.php#L339

is not doubled up. The `$match->item(0)` bit here is already returning a text node and the call to `appendChild` is adding another instance of the DOI to it.  You can remedy this by changing this line to just 

`if ($match->length) $match->item(0)->appendChild();`

and the original text node will be appended without the double DOI appearing.

**Comment by ewhanson** [comment]
PRs:

- `stable-3_3_0`: merged directly... oops!
- `stable-3_4_0`: pkp/oaiJats#54
- `main`: pkp/oaiJats#55
